/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.76
 * Generated at: 2024-05-01 06:50:36 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.members;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class MainForm_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("jar:file:/C:/java_project/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/mini_project/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1712542756981L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      if (_jspx_meth_c_005fset_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("  <head>  \r\n");
      out.write("    <title>MYHOME</title>\r\n");
      out.write("    <script src=\"http://code.jquery.com/jquery-latest.min.js\"></script>\r\n");
      out.write("    <meta charset=\"utf-8\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("<!-- 캐러셀 -->\r\n");
      out.write("<script src=\"https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js\" ></script>\r\n");
      out.write("<script src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.min.js\" ></script>\r\n");
      out.write("<link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css\" rel=\"stylesheet\" >\r\n");
      out.write("<!-- play icon -->\r\n");
      out.write("<script src=\"https://kit.fontawesome.com/4e5b2f86bb.js\" ></script>\r\n");
      out.write("<!-- 캘린더 import -->\r\n");
      out.write("<script type=\"text/javascript\" src=\"https://cdn.jsdelivr.net/jquery/latest/jquery.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"https://cdn.jsdelivr.net/momentjs/latest/moment.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"https://cdn.jsdelivr.net/npm/daterangepicker/daterangepicker.min.js\"></script>\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"https://cdn.jsdelivr.net/npm/daterangepicker/daterangepicker.css\" />\r\n");
      out.write("<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/util/MainFormCalendar.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<!-- css 적용 -->\r\n");
      out.write("<link rel=\"stylesheet\" href=\"../style/css/flaticon.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"../style/css/style.css\">\r\n");
      out.write("<!-- 구글 폰트 -->\r\n");
      out.write("<link rel=\"preconnect\" href=\"https://fonts.googleapis.com\">\r\n");
      out.write("<link rel=\"preconnect\" href=\"https://fonts.gstatic.com\">\r\n");
      out.write("<link href=\"https://fonts.googleapis.com/css2?family=Noto+Sans+KR:wght@100..900&display=swap\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write("/* 폰트 적용 */\r\n");
      out.write("h1, h2, h3, h4, h5, span, a, p, button {\r\n");
      out.write("	font-family: \"Noto Sans KR\", sans-serif;\r\n");
      out.write("	font-optical-sizing: auto;\r\n");
      out.write("	font-weight: <weight>;\r\n");
      out.write("	font-style: normal;\r\n");
      out.write("}\r\n");
      out.write("	.carousel h5 {\r\n");
      out.write("		color: #fff;\r\n");
      out.write("	}\r\n");
      out.write("	.carousel h5, .carousel p {\r\n");
      out.write("		font-size: 16pt;\r\n");
      out.write("	}\r\n");
      out.write("	.eng {\r\n");
      out.write("		font-size: 14pt;\r\n");
      out.write("		font-family: \"Rajdhani\", sans-serif;\r\n");
      out.write("  		font-weight: 400;\r\n");
      out.write("  		font-style: normal;\r\n");
      out.write("	}\r\n");
      out.write("	\r\n");
      out.write("/* 검색 폼 */\r\n");
      out.write("	.searchbox{\r\n");
      out.write("		width: 90%;\r\n");
      out.write("		display: flex;\r\n");
      out.write("		justify-content: center;\r\n");
      out.write("		margin: 20px auto;\r\n");
      out.write("		height: 100px;\r\n");
      out.write("		font-size: 16pt;\r\n");
      out.write("	}\r\n");
      out.write("	.searchbox form{\r\n");
      out.write("		display: flex;\r\n");
      out.write("	}\r\n");
      out.write("	.searchbox form > div {\r\n");
      out.write("		flex: 2;\r\n");
      out.write("		margin: 10px 5px;\r\n");
      out.write("		\r\n");
      out.write("	}\r\n");
      out.write("	.searchbox form > button{\r\n");
      out.write("		flex: 3;\r\n");
      out.write("		margin: 10px auto;\r\n");
      out.write("	}\r\n");
      out.write("	.checkinbox{\r\n");
      out.write("		flex: 2;\r\n");
      out.write("		display: inline-block;\r\n");
      out.write("		margin: 0 auto;\r\n");
      out.write("	}\r\n");
      out.write("	.searchbox input, .searchbox select{\r\n");
      out.write("		flex: 2;\r\n");
      out.write("		width: 100%;\r\n");
      out.write("		border: none;\r\n");
      out.write("	}\r\n");
      out.write("	.checkoutbox{\r\n");
      out.write("		display: inline-block;\r\n");
      out.write("		flex: 2;\r\n");
      out.write("		margin: auto auto;\r\n");
      out.write("	}\r\n");
      out.write("	.roombox{\r\n");
      out.write("		display: inline-block;\r\n");
      out.write("		flex: 2;\r\n");
      out.write("		height: 80px;\r\n");
      out.write("		margin: 0 auto;\r\n");
      out.write("	}\r\n");
      out.write("	.headCountbox{\r\n");
      out.write("		display: inline-block;\r\n");
      out.write("		margin: 0 auto;\r\n");
      out.write("	}\r\n");
      out.write("	.searchbox_button{\r\n");
      out.write(" 		display: inline-block;\r\n");
      out.write(" 		line-height: 60px;\r\n");
      out.write("		height: 80px;\r\n");
      out.write("		border: none;\r\n");
      out.write("		background-color: #8d703b;\r\n");
      out.write("		color: #fff;\r\n");
      out.write("	}\r\n");
      out.write("	.searchbox_button:hover{\r\n");
      out.write(" 		background-color: #000;\r\n");
      out.write("	}\r\n");
      out.write("	.searchbox_button:active{\r\n");
      out.write(" 		background-color: ##78d5ef;\r\n");
      out.write("	}\r\n");
      out.write("	\r\n");
      out.write("	/* main_1 */\r\n");
      out.write("	.main_1 {\r\n");
      out.write("		display: flex;\r\n");
      out.write("		width: 80%;\r\n");
      out.write("		margin: 50px auto;\r\n");
      out.write("	}\r\n");
      out.write("	.main_1 > div{\r\n");
      out.write("		flex:1;\r\n");
      out.write("	}\r\n");
      out.write("	.main_1 >div:nth-child(1) {\r\n");
      out.write("		display: flex;\r\n");
      out.write("		width: 50%;\r\n");
      out.write("		text-align: center;\r\n");
      out.write("		align-items: center;\r\n");
      out.write("		justify-content: center;\r\n");
      out.write("	}\r\n");
      out.write("	.main_1 >div:nth-child(1) > span {\r\n");
      out.write("		display: block;\r\n");
      out.write("	}\r\n");
      out.write("	\r\n");
      out.write("	.main_1 >div:nth-child(2) {\r\n");
      out.write("		width: 50%;\r\n");
      out.write("	}\r\n");
      out.write("	.playicon{\r\n");
      out.write("		display: flex;\r\n");
      out.write("		justify-content: center;\r\n");
      out.write("		align-items: center;\r\n");
      out.write("		width: 80px;\r\n");
      out.write("		height: 80px;\r\n");
      out.write("		border-radius: 50%;\r\n");
      out.write("		background-color: #8d703b;\r\n");
      out.write("		margin: auto;\r\n");
      out.write("	}\r\n");
      out.write("	\r\n");
      out.write("	/* main_2 */\r\n");
      out.write("	.main_2{\r\n");
      out.write("		display: flex;\r\n");
      out.write("		width: 80%;\r\n");
      out.write("		margin: 20px auto;\r\n");
      out.write("	}\r\n");
      out.write("	.main_2 > div{\r\n");
      out.write("		flex: 1;\r\n");
      out.write("		text-align: center;\r\n");
      out.write("		margin: 0 10px;\r\n");
      out.write("	}\r\n");
      out.write("	\r\n");
      out.write("	.round{\r\n");
      out.write("		display: flex;\r\n");
      out.write("		align-items: center;\r\n");
      out.write("		justify-content: center;\r\n");
      out.write("		width: 100px;\r\n");
      out.write("		height: 100px;\r\n");
      out.write("		background-color: #f6f2ea;\r\n");
      out.write("		border-radius: 50%;\r\n");
      out.write("		margin: 0 auto;\r\n");
      out.write("	}\r\n");
      out.write("	.round > span{\r\n");
      out.write("		font-size: 30pt;\r\n");
      out.write("		color: #8d703b;\r\n");
      out.write("		margin: 0 auto;\r\n");
      out.write("	}\r\n");
      out.write("	\r\n");
      out.write("	/* roomList */\r\n");
      out.write("	.roomList{\r\n");
      out.write("		width: 70%;\r\n");
      out.write("		margin: 20px auto;\r\n");
      out.write("	}\r\n");
      out.write("	.OurRoom{\r\n");
      out.write("		display: block;\r\n");
      out.write("		width: 100%;\r\n");
      out.write("		margin: 0 auto;\r\n");
      out.write("		text-align: center;\r\n");
      out.write("	}\r\n");
      out.write("	.roompack{\r\n");
      out.write("		display: flex;\r\n");
      out.write("		flex-wrap: wrap; \r\n");
      out.write("		justify-content: center;\r\n");
      out.write("		margin: 0 auto;\r\n");
      out.write("	}\r\n");
      out.write("	.roompack > .room {\r\n");
      out.write("		margin: 10px 20px;\r\n");
      out.write("		width: 500px;\r\n");
      out.write("		aspect-ratio: 16 / 9;\r\n");
      out.write("	}\r\n");
      out.write("\r\n");
      out.write("	/* 모달 */\r\n");
      out.write("	.modal {\r\n");
      out.write("		display: none;\r\n");
      out.write("		position: fixed;\r\n");
      out.write("		z-index: 1;\r\n");
      out.write("		left: 0;\r\n");
      out.write("		top: 0;\r\n");
      out.write("		width: 100%;\r\n");
      out.write("		height: 100%;\r\n");
      out.write("		overflow: auto;\r\n");
      out.write("		background-color: rgba(0, 0, 0, 0.5);\r\n");
      out.write("	}\r\n");
      out.write("	.modal-content {\r\n");
      out.write("		background-color: #fefefe;\r\n");
      out.write("		margin: 15% auto;\r\n");
      out.write("		padding: 20px;\r\n");
      out.write("		border: 1px solid #888;\r\n");
      out.write("		width: 80%;\r\n");
      out.write("	}\r\n");
      out.write("	.close {\r\n");
      out.write("		color: #aaa;\r\n");
      out.write("		float: right;\r\n");
      out.write("		font-size: 28px;\r\n");
      out.write("		font-weight: bold;\r\n");
      out.write("	}\r\n");
      out.write("	.close:hover, .close:focus {\r\n");
      out.write("	color: black;\r\n");
      out.write("	text-decoration: none;\r\n");
      out.write("	cursor: pointer;\r\n");
      out.write("}\r\n");
      out.write(".playicon {\r\n");
      out.write("	border-radius:0%;\r\n");
      out.write("    display: block;\r\n");
      out.write("    width: 100%; /* 적절한 크기로 조절 */\r\n");
      out.write("    height: 50%;\r\n");
      out.write("    padding-top: 56.25%; /* 16:9 비율 */\r\n");
      out.write("    background-size: cover;\r\n");
      out.write("    position: relative;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".fa-play {\r\n");
      out.write("    position: absolute;\r\n");
      out.write("    top: 50%;\r\n");
      out.write("    left: 50%;\r\n");
      out.write("    transform: translate(-50%, -50%);\r\n");
      out.write("    font-size: 48px; /* 아이콘 크기 조절 가능 */\r\n");
      out.write("}\r\n");
      out.write("#carouselouter{\r\n");
      out.write("	width: 100%;\r\n");
      out.write("	height: 800px;\r\n");
      out.write("	overflow: hidden;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("</style>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("document.addEventListener(\"DOMContentLoaded\", function() {\r\n");
      out.write("	var modalBtn = document.getElementById(\"modalBtn\"); // HTML에 modalBtn ID를 가진 요소 추가해야 함\r\n");
      out.write("	var modal = document.getElementById(\"myModal\"); // HTML에 myModal ID를 가진 요소 추가해야 함\r\n");
      out.write("	var closeBtn = document.getElementsByClassName(\"close\")[0]; // closeBtn을 클래스로 찾는 것으로 수정\r\n");
      out.write("	\r\n");
      out.write("	modalBtn.onclick = function(){\r\n");
      out.write("		modal.style.display = \"block\";\r\n");
      out.write("		video.src = \"https://www.youtube.com/embed/f2yvUavQ_ZY?autoplay=1\";\r\n");
      out.write("	}\r\n");
      out.write("	\r\n");
      out.write("	closeBtn.onclick = function(){\r\n");
      out.write("		modal.style.display = \"none\";\r\n");
      out.write("		video.src = \"\";\r\n");
      out.write("	}\r\n");
      out.write("	window.onclick = function(event) {\r\n");
      out.write("		if(event.target == modal){\r\n");
      out.write("			modal.style.display = \"none\";\r\n");
      out.write("			video.src = \"\";\r\n");
      out.write("		}\r\n");
      out.write("	}\r\n");
      out.write("});\r\n");
      out.write("\r\n");
      out.write("document.getElementById(\"modalBtn\").addEventListener(\"click\", function(event) {\r\n");
      out.write("    event.preventDefault();\r\n");
      out.write("});\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("	");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/include/Header.jsp", out, false);
      out.write("\r\n");
      out.write("	<!-- END nav -->\r\n");
      out.write("	<div id=\"carouselouter\">\r\n");
      out.write("		<div id=\"carouselExampleCaptions\" class=\"carousel slide\" style=\"width: 80%; margin: 0 auto; height: 100% \">\r\n");
      out.write("			<div class=\"carousel-indicators\">\r\n");
      out.write("				<button type=\"button\" data-bs-target=\"#carouselExampleCaptions\"\r\n");
      out.write("					data-bs-slide-to=\"0\" class=\"active\" aria-current=\"true\"\r\n");
      out.write("					aria-label=\"Slide 1\"></button>\r\n");
      out.write("				<button type=\"button\" data-bs-target=\"#carouselExampleCaptions\"\r\n");
      out.write("					data-bs-slide-to=\"1\" aria-label=\"Slide 2\"></button>\r\n");
      out.write("				<button type=\"button\" data-bs-target=\"#carouselExampleCaptions\"\r\n");
      out.write("					data-bs-slide-to=\"2\" aria-label=\"Slide 3\"></button>\r\n");
      out.write("				<button type=\"button\" data-bs-target=\"#carouselExampleCaptions\"\r\n");
      out.write("					data-bs-slide-to=\"3\" aria-label=\"Slide 4\"></button>\r\n");
      out.write("				<button type=\"button\" data-bs-target=\"#carouselExampleCaptions\"\r\n");
      out.write("					data-bs-slide-to=\"4\" aria-label=\"Slide 5\"></button>\r\n");
      out.write("				<button type=\"button\" data-bs-target=\"#carouselExampleCaptions\"\r\n");
      out.write("					data-bs-slide-to=\"5\" aria-label=\"Slide 6\"></button>\r\n");
      out.write("			</div>\r\n");
      out.write("			<div class=\"carousel-inner\">\r\n");
      out.write("				<div class=\"carousel-item active\" data-bs-interval=\"10000\">\r\n");
      out.write("					<img alt=\"\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/style/images/testroom-1.jpg\" width=\"100%\" >\r\n");
      out.write("					<div class=\"carousel-caption d-none d-md-block\">\r\n");
      out.write("						<h5>우리집에 놀러와</h5>\r\n");
      out.write("						<p class=\"eng\">Hotels & Resorts</p>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"carousel-item\">\r\n");
      out.write("					<img alt=\"\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/style/images/testroom-2.jpg\" width=\"100%\" >\r\n");
      out.write("					<div class=\"carousel-caption d-none d-md-block\">\r\n");
      out.write("						<h5>나만의 숲 속 아지트, 우리집에서 삶의 쉼표를 찾아 보세요.</h5>\r\n");
      out.write("						<p class=\"eng\">Hotels & Resorts</p>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"carousel-item\" >\r\n");
      out.write("					<img alt=\"\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/style/images/testroom-3.jpg\" width=\"100%\" >\r\n");
      out.write("					<div class=\"carousel-caption d-none d-md-block\">\r\n");
      out.write("						<h5>감각적 인테리어와 최신의 테크놀로지가 선보이는 <br>새로운 라이프 스타일 트렌드를 경험하세요.</h5>\r\n");
      out.write("						<p class=\"eng\">Hotels & Resorts</p>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("					<div class=\"carousel-item\" >\r\n");
      out.write("					<img alt=\"\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/style/images/testroom-4.jpg\" width=\"100%\" >\r\n");
      out.write("					<div class=\"carousel-caption d-none d-md-block\">\r\n");
      out.write("						<h5>생동감 넘치는 색다른 여행의 시작.</h5>\r\n");
      out.write("						<p class=\"eng\">Hotels & Resorts</p>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("					<div class=\"carousel-item\" >\r\n");
      out.write("					<img alt=\"\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/style/images/testroom-5.jpg\" width=\"100%\" >\r\n");
      out.write("					<div class=\"carousel-caption d-none d-md-block\">\r\n");
      out.write("						<h5>자연의 편안함과 감동적인 서비스가 마음까지 따뜻해지는 행복한 경험을 선사합니다.</h5>\r\n");
      out.write("						<p class=\"eng\">Hotels & Resorts</p>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("					<div class=\"carousel-item\" >\r\n");
      out.write("					<img alt=\"\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/style/images/testroom-6.jpg\" width=\"100%\" >\r\n");
      out.write("					<div class=\"carousel-caption d-none d-md-block\">\r\n");
      out.write("						<h5>최고의 순간을 경험하세요</h5>\r\n");
      out.write("						<p class=\"eng\">Hotels & Resorts</p>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("			<button class=\"carousel-control-prev\" type=\"button\"\r\n");
      out.write("				data-bs-target=\"#carouselExampleCaptions\" data-bs-slide=\"prev\">\r\n");
      out.write("				<span class=\"carousel-control-prev-icon\" aria-hidden=\"true\"></span> <span\r\n");
      out.write("					class=\"visually-hidden\">Previous</span>\r\n");
      out.write("			</button>\r\n");
      out.write("			<button class=\"carousel-control-next\" type=\"button\"\r\n");
      out.write("				data-bs-target=\"#carouselExampleCaptions\" data-bs-slide=\"next\">\r\n");
      out.write("				<span class=\"carousel-control-next-icon\" aria-hidden=\"true\"></span> <span\r\n");
      out.write("					class=\"visually-hidden\">Next</span>\r\n");
      out.write("			</button>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("	\r\n");
      out.write("	<!-- 메인 검색 폼 -->\r\n");
      out.write("	<div class=\"searchbox\">\r\n");
      out.write("		<form action=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/RoomFilterList?type=main\" method=\"get\">\r\n");
      out.write("			<div class=\"checkinbox\">\r\n");
      out.write("				<label>체크인</label><br>\r\n");
      out.write("				<input type=\"text\" name=\"checkIn\" id=\"checkInDate\" placeholder=\"체크인 날짜\" readonly>\r\n");
      out.write("			</div>\r\n");
      out.write("			<div class=\"checkoutbox\">\r\n");
      out.write("				<label>체크아웃</label><br>\r\n");
      out.write("				<input type=\"text\" name=\"checkOut\" id=\"checkOutDate\" placeholder=\"체크아웃 날짜\" readonly>\r\n");
      out.write("			</div>\r\n");
      out.write("			<div class=\"roombox\">\r\n");
      out.write("				<label>객실</label><br>\r\n");
      out.write("				<select name=\"roomType\">\r\n");
      out.write("					<option value=\"default\" selected>선택</option>\r\n");
      out.write("					<option value=\"Superior\">슈페리어 룸</option>\r\n");
      out.write("					<option value=\"Deluxe\">디럭스 룸</option>\r\n");
      out.write("					<option value=\"GrandDeluxe\">그랜드 디럭스 룸</option>\r\n");
      out.write("					<option value=\"JuniorSuite\">주니어 스위트 룸</option>\r\n");
      out.write("					<option value=\"CornerSuite\">코너스 스위트 룸</option>\r\n");
      out.write("					<option value=\"SuperiorSuite\">슈페리어 스위트 룸</option>\r\n");
      out.write("					<option value=\"RoyalSuite\">로열 스위트 룸</option>\r\n");
      out.write("					<option value=\"PresidentialSuite\">프레지덴셜 스위트 룸</option>\r\n");
      out.write("					<option value=\"Connecting\">커넥팅 룸</option>\r\n");
      out.write("				</select>\r\n");
      out.write("			</div>\r\n");
      out.write("			<div class=\"headCountbox\">\r\n");
      out.write("				<label>인원 수</label><br>\r\n");
      out.write("				<select name=\"headCount\">\r\n");
      out.write("					<option value=\"1\">1 명</option>\r\n");
      out.write("					<option value=\"2\" selected>2 명</option>\r\n");
      out.write("					<option value=\"3\">3 명</option>\r\n");
      out.write("					<option value=\"4\">4 명</option>\r\n");
      out.write("					<option value=\"5\">5 명</option>\r\n");
      out.write("					<option value=\"6\">6 명</option>\r\n");
      out.write("					<option value=\"7\">7 명</option>\r\n");
      out.write("					<option value=\"8\">8 명</option>\r\n");
      out.write("					<option value=\"9\">9 명</option>\r\n");
      out.write("					<option value=\"10\">10 명</option>\r\n");
      out.write("				</select>\r\n");
      out.write("			</div>\r\n");
      out.write("			<input type=\"hidden\" name=\"type\" value=\"main\" >\r\n");
      out.write("			\r\n");
      out.write("			<button type=\"submit\" class=\"searchbox_button\" >객실 검색</button>\r\n");
      out.write("		</form>\r\n");
      out.write("	</div>\r\n");
      out.write("	<!-- 모달창 -->\r\n");
      out.write("	<div id=\"myModal\" class=\"modal\">\r\n");
      out.write("		<div class=\"modal-content\">\r\n");
      out.write("			<span class=\"close\">&times;</span>\r\n");
      out.write("			\r\n");
      out.write("			<iframe width=\"100%\"  style=\"aspect-ratio: 16 / 9;\" id=\"video\" src=\"https://www.youtube.com/embed/f2yvUavQ_ZY?autoplay=1\" frameborder=\"0\" allowfullscreen ></iframe>\r\n");
      out.write("			\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("	<!-- 리조트 실행 --> \r\n");
      out.write("	<section class=\"main_1\">\r\n");
      out.write("    <div class=\"leftside\">\r\n");
      out.write("        <a class=\"playicon\" id=\"modalBtn\" href=\"#\" style=\"background-image:url('");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/style/images/some.jpg');\">\r\n");
      out.write("            <i class=\"fa-solid fa-play fa-xl\" style=\"color: #ffffff;\"></i>\r\n");
      out.write("        </a>\r\n");
      out.write("    </div>\r\n");
      out.write("	\r\n");
      out.write("  \r\n");
      out.write("	\r\n");
      out.write("		<div style=\" margin-left: 70px;\" class=\"rightside\" >\r\n");
      out.write("			<div>\r\n");
      out.write("				<span class=\"eng\">Welcome to OurHome Hotel</span>\r\n");
      out.write("				<h2>색다른 경험이 될, <br>우리집 리조트</h2>\r\n");
      out.write("			</div>\r\n");
      out.write("			<div>\r\n");
      out.write("				<p>당신에게 쉼표의 시간은 언제인가요? 본디 쉼표란 '쉬어간다'는 의미와 함께, 음악에서는 빽빽한 음표 사이에 위치한 쉼표가 이전과는 다른 리듬을 만들어 내는 역할을 하기도 합니다. 비교할 수 없는 평온함과 여유로움을 통해 잠들어 있던 감각을 깨우는 음악 속 쉼표 같은 휴식을 가질 수 있는 곳, 우리집 리조트로 여러분을 초대합니다.</p>\r\n");
      out.write("				<p>누구나 평생 한 번쯤 경험하고 싶어 하는 지상 최고의 낙원. 빌라는 최상급 수준의 럭셔리함을 갖추고 있습니다. 우리집 리조트 내 모든 객실 중 가장 넓은 규모가 특징인 이곳은 비교할 수 없는 풍요로움은 물론, 내집에서 느껴지는 안락함도 동시에 느낄 수 있는 디테일로 구성되어 있습니다. 모든 고객에게 차별화된 경험을 제공하기 위해 세심하게 관리됩니다. 럭셔리한 하루와 함께 최대한의 프라이버시를 보장받고 싶은 개인 여행자부터 가족 또는 연인이 온종일 머무르기에도 완벽한 공간입니다.</p>\r\n");
      out.write("				<p>VIP 전용 게이트를 통해 출입하고, 독립된 형태의 발코니에서 친밀한 야외 디너를 즐기며 활력을 되찾아 주는 자쿠지와 스파 시설이 딸린 개인용 야외 수영장에서 한적한 시간을 즐겨보세요. 또한 빌라 투숙객들에게만 제공되는 버틀러 서비스는 고객별 맞춤형으로 제공되어 가장 편안한 휴식을 돕습니다. 머무는 동안 비교할 수 없는 품격과 세련미에 흠뻑 빠져보세요.</p>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</section>\r\n");
      out.write("	\r\n");
      out.write("	<section class=\"main_2\">\r\n");
      out.write("		<div>\r\n");
      out.write("			<div class=\"round\">\r\n");
      out.write("				<span class=\"flaticon-reception-bell\"></span>\r\n");
      out.write("			</div>\r\n");
      out.write("			<div>\r\n");
      out.write("				<h3>24/7 Front Desk</h3>\r\n");
      out.write("				<p>언제든 연락가능한 프론트 데스크, 편안함을 누리세요</p>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("		\r\n");
      out.write("		<div>\r\n");
      out.write("			<div class=\"round\">\r\n");
      out.write("				<span class=\"flaticon-serving-dish\"></span>\r\n");
      out.write("			</div>\r\n");
      out.write("			<div>\r\n");
      out.write("				<h3>Restaurant Bar</h3>\r\n");
      out.write("				<p>풍성한 맛과 아름다운 분위기, 레스토랑바에서 특별한 순간을 만나보세요!</p>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("		\r\n");
      out.write("		<div>\r\n");
      out.write("			<div class=\"round\">\r\n");
      out.write("				<span class=\"flaticon-car\"></span>\r\n");
      out.write("			</div>\r\n");
      out.write("			<div>\r\n");
      out.write("				<h3>Transfer Services</h3>\r\n");
      out.write("				<p>여행의 시작부터 끝까지, 우리집 리조트는 언제나 여러분을 지원합니다.</p>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("		\r\n");
      out.write("		<div>\r\n");
      out.write("			<div class=\"round\">\r\n");
      out.write("				<span class=\"flaticon-spa\"></span>\r\n");
      out.write("			</div>\r\n");
      out.write("			<div>\r\n");
      out.write("				<h3>Spa Suites</h3>\r\n");
      out.write("				<p>스파 스위트룸에서 특별한 시간을 보내며 몸과 마음을 풀어보세요.</p>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</section>\r\n");
      out.write("	\r\n");
      out.write("	<!-- 객실 리스트 -->\r\n");
      out.write("	<section class=\"roomList\">\r\n");
      out.write("		<div >\r\n");
      out.write("			<div class=\"OurRoom\">\r\n");
      out.write("				<h2>Our Rooms</h2>\r\n");
      out.write("			</div>\r\n");
      out.write("			<div class=\"roompack\">\r\n");
      out.write("				<div class=\"room\">\r\n");
      out.write("    				<a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/RoomFilterList?type=mainImg&roomType=Superior\" class=\"img d-flex justify-content-center align-items-center\" style=\"background-image: url(");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/data/Superior-1.jpg);\"> <!-- 방 이미지 출력 -->\r\n");
      out.write("    					<div class=\"icon d-flex justify-content-center align-items-center\">\r\n");
      out.write("    						<span><i class=\"fa-solid fa-magnifying-glass fa-sm\"></i></span>\r\n");
      out.write("    					</div>\r\n");
      out.write("    				</a>\r\n");
      out.write("    				<div class=\"text p-3 text-center\">\r\n");
      out.write("    					<h3 class=\"mb-3\"><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/RoomFilterList?type=mainImg&roomType=Superior\"> 슈페리어 </a></h3>\r\n");
      out.write("    					<p><span class=\"price mr-3\">200,000원</span> <span class=\"per\"> 1박 </span></p>\r\n");
      out.write("    					<hr>\r\n");
      out.write("    					<p class=\"pt-1\"><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/RoomFilterList?type=mainImg&roomType=Superior\" class=\"btn-custom\">방 상세보기<span> <i class=\"fa-solid fa-arrow-right-long fa-sm\"></i></span></a></p>\r\n");
      out.write("    				</div>\r\n");
      out.write("    			</div>\r\n");
      out.write("				<div class=\"room\">\r\n");
      out.write("    				<a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/RoomFilterList?type=mainImg&roomType=Deluxe\" class=\"img d-flex justify-content-center align-items-center\" style=\"background-image: url(");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/data/Deluxe-1.jpg);\"> <!-- 방 이미지 출력 -->\r\n");
      out.write("    					<div class=\"icon d-flex justify-content-center align-items-center\">\r\n");
      out.write("    						<span><i class=\"fa-solid fa-magnifying-glass fa-sm\"></i></span>\r\n");
      out.write("    					</div>\r\n");
      out.write("    				</a>\r\n");
      out.write("    				<div class=\"text p-3 text-center\">\r\n");
      out.write("    					<h3 class=\"mb-3\"><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/RoomFilterList?type=mainImg&roomType=Deluxe\"> 디럭스 </a></h3>\r\n");
      out.write("    					<p><span class=\"price mr-3\">260,000원</span> <span class=\"per\"> 1박</span></p>\r\n");
      out.write("    					<hr>\r\n");
      out.write("    					<p class=\"pt-1\"><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/RoomFilterList?type=mainImg&roomType=Deluxe\" class=\"btn-custom\">방 상세보기<span> <i class=\"fa-solid fa-arrow-right-long fa-sm\"></i></span></a></p>\r\n");
      out.write("    				</div>\r\n");
      out.write("    			</div>\r\n");
      out.write("			</div>\r\n");
      out.write("			<div class=\"roompack\">\r\n");
      out.write("				<div class=\"room\">\r\n");
      out.write("    				<a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/RoomFilterList?type=mainImg&roomType=GrandDeluxe\" class=\"img d-flex justify-content-center align-items-center\" style=\"background-image: url(");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/data/GrandDeluxe-1.jpg);\"> <!-- 방 이미지 출력 -->\r\n");
      out.write("    					<div class=\"icon d-flex justify-content-center align-items-center\">\r\n");
      out.write("    						<span><i class=\"fa-solid fa-magnifying-glass fa-sm\"></i></span>\r\n");
      out.write("    					</div>\r\n");
      out.write("    				</a>\r\n");
      out.write("    				<div class=\"text p-3 text-center\">\r\n");
      out.write("    					<h3 class=\"mb-3\"><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/RoomFilterList?type=mainImg&roomType=GrandDeluxe\"> 그랜드 디럭스 </a></h3>\r\n");
      out.write("    					<p><span class=\"price mr-3\">640,000원</span> <span class=\"per\"> 1박</span></p>\r\n");
      out.write("    					<hr>\r\n");
      out.write("    					<p class=\"pt-1\"><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/RoomFilterList?type=mainImg&roomType=GrandDeluxe\" class=\"btn-custom\">방 상세보기<span> <i class=\"fa-solid fa-arrow-right-long fa-sm\"></i></span></a></p>\r\n");
      out.write("    				</div>\r\n");
      out.write("    			</div>\r\n");
      out.write("				<div class=\"room\">\r\n");
      out.write("    				<a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/RoomFilterList?type=mainImg&roomType=JuniorSuite\" class=\"img d-flex justify-content-center align-items-center\" style=\"background-image: url(");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/data/JuniorSuite-1.jpg);\"> <!-- 방 이미지 출력 -->\r\n");
      out.write("    					<div class=\"icon d-flex justify-content-center align-items-center\">\r\n");
      out.write("    						<span><i class=\"fa-solid fa-magnifying-glass fa-sm\"></i></span>\r\n");
      out.write("    					</div>\r\n");
      out.write("    				</a>\r\n");
      out.write("    				<div class=\"text p-3 text-center\">\r\n");
      out.write("    					<h3 class=\"mb-3\"><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/RoomFilterList?type=mainImg&roomType=JuniorSuite\"> 주니어 스위트 </a></h3>\r\n");
      out.write("    					<p><span class=\"price mr-3\">440,000원</span> <span class=\"per\"> 1박</span></p>\r\n");
      out.write("    					<hr>\r\n");
      out.write("    					<p class=\"pt-1\"><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/RoomFilterList?type=mainImg&roomType=JuniorSuite\" class=\"btn-custom\">방 상세보기<span> <i class=\"fa-solid fa-arrow-right-long fa-sm\"></i></span></a></p>\r\n");
      out.write("    				</div>\r\n");
      out.write("    			</div>\r\n");
      out.write("			</div>\r\n");
      out.write("			<div class=\"roompack\">\r\n");
      out.write("				<div class=\"room\">\r\n");
      out.write("    				<a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/RoomFilterList?type=mainImg&roomType=CornerSuite\" class=\"img d-flex justify-content-center align-items-center\" style=\"background-image: url(");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/data/CornerSuite-1.jpg);\"> <!-- 방 이미지 출력 -->\r\n");
      out.write("    					<div class=\"icon d-flex justify-content-center align-items-center\">\r\n");
      out.write("    						<span><i class=\"fa-solid fa-magnifying-glass fa-sm\"></i></span>\r\n");
      out.write("    					</div>\r\n");
      out.write("    				</a>\r\n");
      out.write("    				<div class=\"text p-3 text-center\">\r\n");
      out.write("    					<h3 class=\"mb-3\"><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/RoomFilterList?type=mainImg&roomType=CornerSuite\"> 코너스 스위트 </a></h3>\r\n");
      out.write("    					<p><span class=\"price mr-3\">420,000원</span> <span class=\"per\"> 1박</span></p>\r\n");
      out.write("    					<hr>\r\n");
      out.write("    					<p class=\"pt-1\"><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/RoomFilterList?type=mainImg&roomType=CornerSuite\" class=\"btn-custom\">방 상세보기<span> <i class=\"fa-solid fa-arrow-right-long fa-sm\"></i></span></a></p>\r\n");
      out.write("    				</div>\r\n");
      out.write("    			</div>\r\n");
      out.write("				<div class=\"room\">\r\n");
      out.write("    				<a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/RoomFilterList?type=mainImg&roomType=SuperiorSuite\" class=\"img d-flex justify-content-center align-items-center\" style=\"background-image: url(");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/data/SuperiorSuite-1.jpg);\"> <!-- 방 이미지 출력 -->\r\n");
      out.write("    					<div class=\"icon d-flex justify-content-center align-items-center\">\r\n");
      out.write("    						<span><i class=\"fa-solid fa-magnifying-glass fa-sm\"></i></span>\r\n");
      out.write("    					</div>\r\n");
      out.write("    				</a>\r\n");
      out.write("    				<div class=\"text p-3 text-center\">\r\n");
      out.write("    					<h3 class=\"mb-3\"><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/RoomFilterList?type=mainImg&roomType=SuperiorSuite\"> 슈페리어 스위트 </a></h3>\r\n");
      out.write("    					<p><span class=\"price mr-3\">510,000원</span> <span class=\"per\"> 1박</span></p>\r\n");
      out.write("    					<hr>\r\n");
      out.write("    					<p class=\"pt-1\"><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/RoomFilterList?type=mainImg&roomType=SuperiorSuite\" class=\"btn-custom\">방 상세보기<span> <i class=\"fa-solid fa-arrow-right-long fa-sm\"></i></span></a></p>\r\n");
      out.write("    				</div>\r\n");
      out.write("    			</div>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("		\r\n");
      out.write("	</section>\r\n");
      out.write("	\r\n");
      out.write("	");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/include/Footer.jsp", out, false);
      out.write("\r\n");
      out.write("\r\n");
      out.write("  </body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fset_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:set
    org.apache.taglibs.standard.tag.rt.core.SetTag _jspx_th_c_005fset_005f0 = (org.apache.taglibs.standard.tag.rt.core.SetTag) _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.SetTag.class);
    boolean _jspx_th_c_005fset_005f0_reused = false;
    try {
      _jspx_th_c_005fset_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fset_005f0.setParent(null);
      // /members/MainForm.jsp(4,0) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f0.setVar("contextPath");
      // /members/MainForm.jsp(4,0) name = value type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f0.setValue(new org.apache.jasper.el.JspValueExpression("/members/MainForm.jsp(4,0) '${pageContext.request.contextPath }'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${pageContext.request.contextPath }",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      int _jspx_eval_c_005fset_005f0 = _jspx_th_c_005fset_005f0.doStartTag();
      if (_jspx_th_c_005fset_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005fset_005f0);
      _jspx_th_c_005fset_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fset_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fset_005f0_reused);
    }
    return false;
  }
}
