/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.76
 * Generated at: 2024-05-01 06:52:25 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.members;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class Payment_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("jar:file:/C:/java_project/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/mini_project/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1712542756981L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.release();
    _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      if (_jspx_meth_c_005fset_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>결제 페이지</title>\r\n");
      out.write("<link href=\"https://fonts.googleapis.com/css2?family=Roboto:wght@400;500&display=swap\" rel=\"stylesheet\">\r\n");
      out.write("<script src=\"http://code.jquery.com/jquery-latest.min.js\"></script>\r\n");
      out.write("<!-- css 적용 -->\r\n");
      out.write("<link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/style/css/flaticon.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/style/css/style.css\">\r\n");
      out.write("\r\n");
      out.write("<style>\r\n");
      out.write("    body {\r\n");
      out.write("        font-family: 'Roboto', sans-serif;\r\n");
      out.write("        margin: 0;\r\n");
      out.write("        padding: 0;\r\n");
      out.write("        background-color: #f5f5f5;\r\n");
      out.write("    }\r\n");
      out.write("    .container {\r\n");
      out.write("        width: 100%;\r\n");
      out.write("        max-width: 1100px;\r\n");
      out.write("        margin: 0 auto;\r\n");
      out.write("        padding: 20px 15px;\r\n");
      out.write("        box-sizing: border-box;\r\n");
      out.write("    }\r\n");
      out.write("    .row {\r\n");
      out.write("        display: flex;\r\n");
      out.write("        \r\n");
      out.write("    }\r\n");
      out.write("    #leftDiv, #rightDiv {\r\n");
      out.write("        background-color: #fff;\r\n");
      out.write("        border-radius: 10px;\r\n");
      out.write("        box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);\r\n");
      out.write("        margin: 0 10px;\r\n");
      out.write("        padding: 20px;\r\n");
      out.write("    }\r\n");
      out.write("    #leftDiv {\r\n");
      out.write("        width: 50%;\r\n");
      out.write("    }\r\n");
      out.write("    #rightDiv {\r\n");
      out.write("    	width: 40%;\r\n");
      out.write("    }\r\n");
      out.write("    .table-container {\r\n");
      out.write("        margin-bottom: 20px;\r\n");
      out.write("    }\r\n");
      out.write("    table {\r\n");
      out.write("        width: 100%;\r\n");
      out.write("    }\r\n");
      out.write("    td {\r\n");
      out.write("        padding: 10px;\r\n");
      out.write("    }\r\n");
      out.write("    hr {\r\n");
      out.write("        border: none;\r\n");
      out.write("        border-top: 1px solid #ccc;\r\n");
      out.write("        margin-top: 20px ;\r\n");
      out.write("    }\r\n");
      out.write("    input[type=\"text\"], button {\r\n");
      out.write("        width: calc(100% - 22px);\r\n");
      out.write("        padding: 5px;\r\n");
      out.write("        border: 1px solid #ccc;\r\n");
      out.write("        border-radius: 5px;\r\n");
      out.write("    }\r\n");
      out.write("    input[type=\"text\"] {\r\n");
      out.write("        margin-bottom: 4px;\r\n");
      out.write("    }\r\n");
      out.write("    .payment-btn {\r\n");
      out.write("        background-color: #00BFFF;\r\n");
      out.write("        color: #fff;\r\n");
      out.write("        font-weight: bold;\r\n");
      out.write("        cursor: pointer;\r\n");
      out.write("    }\r\n");
      out.write("    .return:hover {\r\n");
      out.write("        background-color: #0080FF;\r\n");
      out.write("    }\r\n");
      out.write("       \r\n");
      out.write("    .terms-label {\r\n");
      out.write("        display: flex; /* 플렉스 박스 사용 */\r\n");
      out.write("        align-items: center; /* 수직 정렬 */\r\n");
      out.write("        font-size: 13px; /* 폰트 사이즈 조절 */\r\n");
      out.write("    \r\n");
      out.write("    }\r\n");
      out.write("    .terms-label > span {\r\n");
      out.write("        flex: 1; /* 유동적인 공간을 활용하여 약관 텍스트를 확장 */\r\n");
      out.write("        font-size: 15px; /* 원하는 크기로 설정 */\r\n");
      out.write("    }\r\n");
      out.write("    /* 모달 스타일 */\r\n");
      out.write("    .modal {\r\n");
      out.write("        display: none; /* 기본적으로 모달을 숨김 */\r\n");
      out.write("        position: fixed; /* 위치를 고정 */\r\n");
      out.write("        z-index: 1; /* 다른 요소 위에 표시 */\r\n");
      out.write("        left: 0;\r\n");
      out.write("        top: 0;\r\n");
      out.write("        width: 100%;\r\n");
      out.write("        height: 100%;\r\n");
      out.write("        overflow: auto; /* 스크롤이 발생할 경우 스크롤 허용 */\r\n");
      out.write("        background-color: rgba(0, 0, 0, 0.4); /* 배경을 반투명한 검은색으로 설정 */\r\n");
      out.write("    }\r\n");
      out.write("    /* 모달 내용 */\r\n");
      out.write("    .modal-content {\r\n");
      out.write("        background-color: #fefefe; /* 모달 내용 배경색 */\r\n");
      out.write("        margin: 7% auto; /* 모달을 화면 중앙에 위치, 기존보다 더 위로 조정 */\r\n");
      out.write("        padding: 20px;\r\n");
      out.write("        border: 1px solid #888;\r\n");
      out.write("        width: 25%; /* 모달의 너비 */    \r\n");
      out.write("        border-radius: 10px; /* 모달 내용의 테두리 반경 설정 */\r\n");
      out.write("        box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2); /* 그림자 효과 추가 */\r\n");
      out.write("        height: 50%; /* 모달의 높이를 최대로 설정 */\r\n");
      out.write("        overflow-y: scroll; /* 항상 스크롤바 표시 */\r\n");
      out.write("    }\r\n");
      out.write("    /* 닫기 버튼 */\r\n");
      out.write("    .close {\r\n");
      out.write("        color: #aaa;\r\n");
      out.write("        float: right;\r\n");
      out.write("        font-size: 20px; /* 크기 조정 */\r\n");
      out.write("        font-weight: bold;\r\n");
      out.write("    }\r\n");
      out.write("    .close:hover,\r\n");
      out.write("    .close:focus {\r\n");
      out.write("        color: black;\r\n");
      out.write("        text-decoration: none;\r\n");
      out.write("        cursor: pointer;\r\n");
      out.write("    }\r\n");
      out.write("    \r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("<!-- 약관 확인 스크립트 -->\r\n");
      out.write("<script> \r\n");
      out.write("    // 모달 열기 함수\r\n");
      out.write("    function openModal(filename) {\r\n");
      out.write("        // XMLHttpRequest 객체 생성\r\n");
      out.write("        var xhttp = new XMLHttpRequest();\r\n");
      out.write("        // 요청 완료 후 실행될 함수 지정\r\n");
      out.write("        xhttp.onreadystatechange = function() {\r\n");
      out.write("            if (this.readyState == 4 && this.status == 200) {\r\n");
      out.write("                // 서버로부터 받은 내용을 모달에 표시\r\n");
      out.write("                document.getElementById(\"modalContent\").innerHTML = this.responseText;\r\n");
      out.write("                // 모달 보이도록 설정\r\n");
      out.write("                document.getElementById(\"myModal\").style.display = \"block\";\r\n");
      out.write("            }\r\n");
      out.write("        };\r\n");
      out.write("        // GET 방식으로 요청을 보냄\r\n");
      out.write("        xhttp.open(\"GET\", filename, true);\r\n");
      out.write("        xhttp.send();\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    // 모달 닫기 함수\r\n");
      out.write("    function closeModal() {\r\n");
      out.write("        document.getElementById(\"myModal\").style.display = \"none\";\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    // 사용자가 모달 외부를 클릭하면 모달 닫기\r\n");
      out.write("    window.onclick = function(event) {\r\n");
      out.write("        if (event.target == document.getElementById(\"myModal\")) {\r\n");
      out.write("            closeModal();\r\n");
      out.write("        }\r\n");
      out.write("    }\r\n");
      out.write("</script>\r\n");
      out.write("<script>\r\n");
      out.write("	$(function() {\r\n");
      out.write("		$('#revPaymentForm').submit(function(event) {\r\n");
      out.write("			event.preventDefault();\r\n");
      out.write("			var check1 = document.querySelector('[name=agree3]').checked;\r\n");
      out.write("			var check2 = document.querySelector('[name=agree4]').checked;\r\n");
      out.write("			if(check1 && check2) {\r\n");
      out.write("				var formData = $(this).serialize();\r\n");
      out.write("				$.ajax({\r\n");
      out.write("					method: \"post\",\r\n");
      out.write("					url: \"");
      if (_jspx_meth_c_005furl_005f0(_jspx_page_context))
        return;
      out.write("\",\r\n");
      out.write("					data: formData,\r\n");
      out.write("					dataType: \"text\",\r\n");
      out.write("					success:function(data) {\r\n");
      out.write("						if(data == \"success\") {\r\n");
      out.write("							alert(\"예약이 완료 되었습니다.\");\r\n");
      out.write("							window.location.replace(\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/RevList?type=myInfo\");\r\n");
      out.write("						} else{\r\n");
      out.write("							alert(\"예약 과정에서 오류가 발생했습니다. 잠시 후 다시 시도해주세요.\");\r\n");
      out.write("							window.history.back();\r\n");
      out.write("						}\r\n");
      out.write("					},\r\n");
      out.write("					error:function() {\r\n");
      out.write("						alert(\"오류가 발생했습니다 잠시 후 다시 시도해주세요.\");\r\n");
      out.write("						window.history.back();\r\n");
      out.write("					}\r\n");
      out.write("				});\r\n");
      out.write("				\r\n");
      out.write("			} else {\r\n");
      out.write("				alert(\"모든 약관에 동의해야 합니다.\");\r\n");
      out.write("			}\r\n");
      out.write("			\r\n");
      out.write("			\r\n");
      out.write("		});\r\n");
      out.write("		\r\n");
      out.write("	});\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("    <div id=\"myModal\" class=\"modal\" >\r\n");
      out.write("      <div class=\"modal-content\" >   \r\n");
      out.write("        <span class=\"close\" onclick=\"closeModal()\">&times;</span>\r\n");
      out.write("        <div id=\"modalContent\"  ></div>\r\n");
      out.write("      	<div class=\"button-container\">\r\n");
      out.write("            <button class=\"confirm-button\" onclick=\"closeModal()\">확인</button>         \r\n");
      out.write("        </div>\r\n");
      out.write("        \r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <div class=\"container\" style=\"margin-bottom: 50px;\">\r\n");
      out.write("        ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/include/Header.jsp", out, false);
      out.write("\r\n");
      out.write("        <div class=\"row\" style=\"margin-top: 50px; justify-content: center;\">\r\n");
      out.write("            <div id=\"leftDiv\">\r\n");
      out.write("                <div class=\"table-container\">\r\n");
      out.write("                    <table id=\"payment-table\">\r\n");
      out.write("                        <tr>\r\n");
      out.write("                            <td>주문자 아이디</td>\r\n");
      out.write("                            <td><input type=\"text\" name=\"memId\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${memVO.memId }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" readonly></td>\r\n");
      out.write("                        </tr>\r\n");
      out.write("                        <tr>\r\n");
      out.write("                            <td>주문자 이름</td>\r\n");
      out.write("                            <td><input type=\"text\" name=\"memName\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${memVO.memName }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" readonly></td>\r\n");
      out.write("                        </tr>\r\n");
      out.write("                        <tr>\r\n");
      out.write("                            <td colspan=\"2\"><hr></td>\r\n");
      out.write("                        </tr>\r\n");
      out.write("                        <tr>\r\n");
      out.write("                            <td>주문자 이메일</td>\r\n");
      out.write("                            <td><input type=\"text\" name=\"memEmail\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${memVO.memEmail }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" readonly></td>\r\n");
      out.write("                        </tr>\r\n");
      out.write("                        <tr>\r\n");
      out.write("                            <td>주문자 전화번호</td>\r\n");
      out.write("                            <td><input type=\"text\" name=\"memCall\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${memVO.memCall }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" readonly></td>\r\n");
      out.write("                        </tr>\r\n");
      out.write("                        <tr>\r\n");
      out.write("                            <td colspan=\"2\"><hr>\r\n");
      out.write("                                <label class=\"terms-label\" style=\"margin-top: 50px;\">\r\n");
      out.write("                                    <span >예약 취소 정책.</span>&nbsp;<button style=\"width:26%;\"onclick=\"openModal('");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/clauses/RevCancellation.jsp')\">약관 보기</button><br>\r\n");
      out.write("                                    <input type=\"checkbox\" name=\"agree3\" value=\"yes\" style=\"margin-left: 30px\"  onclick=\"document.querySelector('[name=disagree3]').checked = false;\"> 동의합니다.\r\n");
      out.write("                                    &nbsp;&nbsp;&nbsp;&nbsp;\r\n");
      out.write("                                    <input type=\"checkbox\" name=\"disagree3\" value=\"no\"  onclick=\"document.querySelector('[name=agree3]').checked = false;\"> 동의하지 않습니다.\r\n");
      out.write("                                </label>\r\n");
      out.write("                            </td>\r\n");
      out.write("                        </tr>\r\n");
      out.write("                        <tr>\r\n");
      out.write("                            <td colspan=\"2\">\r\n");
      out.write("                                <label class=\"terms-label\" style=\"margin-top: 20px;\">\r\n");
      out.write("                                    <span>환불 정책.</span><button style=\"width:26%;\"onclick=\"openModal('");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/clauses/Refund.jsp')\">약관 보기</button><br>\r\n");
      out.write("                                    <input type=\"checkbox\" name=\"agree4\" value=\"yes\" style=\"margin-left: 30px\"  onclick=\"document.querySelector('[name=disagree4]').checked = false;\"> 동의합니다.\r\n");
      out.write("                                    &nbsp;&nbsp;&nbsp;&nbsp;\r\n");
      out.write("                                    <input type=\"checkbox\" name=\"disagree4\" value=\"no\"  onclick=\"document.querySelector('[name=agree4]').checked = false;\"> 동의하지 않습니다.\r\n");
      out.write("                                </label>\r\n");
      out.write("                            </td>\r\n");
      out.write("                        </tr>\r\n");
      out.write("                    </table>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div id=\"rightDiv\">\r\n");
      out.write("                <form id=\"revPaymentForm\">\r\n");
      out.write("                    <div class=\"table-container\">\r\n");
      out.write("                        <table>\r\n");
      out.write("                            <tr>\r\n");
      out.write("                                <td>객실</td>\r\n");
      out.write("                                <td><input type=\"text\" name=\"roomName\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${roomName }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" readonly></td>\r\n");
      out.write("                            </tr>\r\n");
      out.write("                            <tr>\r\n");
      out.write("                                <td colspan=\"2\"><hr></td>\r\n");
      out.write("                            </tr>\r\n");
      out.write("                            <tr>\r\n");
      out.write("                                <td>이용 날짜</td>\r\n");
      out.write("                                <td><input type=\"text\" name=\"checkDate\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${revDate }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" readonly></td>\r\n");
      out.write("                            </tr>\r\n");
      out.write("                            <tr>\r\n");
      out.write("                                <td colspan=\"2\"><hr></td>\r\n");
      out.write("                            </tr>\r\n");
      out.write("                            <tr>\r\n");
      out.write("                                <td>인원수</td>\r\n");
      out.write("                                <td><input type=\"text\" name=\"headCount\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${headCount }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" readonly></td>\r\n");
      out.write("                            </tr>\r\n");
      out.write("                            <tr>\r\n");
      out.write("                                <td colspan=\"2\"><hr></td>\r\n");
      out.write("                            </tr>\r\n");
      out.write("                            <tr>\r\n");
      out.write("                                <td>총 요금</td>\r\n");
      out.write("                                <td><input type=\"text\" name=\"totalPrice\" class=\"price\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${totalPrice }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" id=\"totalPrice\" readonly></td>\r\n");
      out.write("                            </tr>\r\n");
      out.write("                            <tr>\r\n");
      out.write("                                <td colspan=\"2\"><hr></td>\r\n");
      out.write("                            </tr>\r\n");
      out.write("                            <tr>\r\n");
      out.write("                                <td align=\"right\" colspan=\"2\" style=\"text-align: center;\">\r\n");
      out.write("                                	<input type=\"hidden\" name=\"roomNo\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${roomNo }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" />\r\n");
      out.write("                                    <button class=\"payment-btn\" type=\"button\"  onclick=\"window.history.back()\" style=\"width: 50%; margin-bottom: 15px; \">돌아가기</button>\r\n");
      out.write("                                    <button type=\"submit\" class=\"payment-btn\" style=\"width: 50%;\">결제</button>\r\n");
      out.write("                                </td>\r\n");
      out.write("                            </tr>\r\n");
      out.write("                        </table>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </form>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/include/Footer.jsp", out, false);
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fset_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:set
    org.apache.taglibs.standard.tag.rt.core.SetTag _jspx_th_c_005fset_005f0 = (org.apache.taglibs.standard.tag.rt.core.SetTag) _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.SetTag.class);
    boolean _jspx_th_c_005fset_005f0_reused = false;
    try {
      _jspx_th_c_005fset_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fset_005f0.setParent(null);
      // /members/Payment.jsp(4,0) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f0.setVar("contextPath");
      // /members/Payment.jsp(4,0) name = value type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f0.setValue(new org.apache.jasper.el.JspValueExpression("/members/Payment.jsp(4,0) '${pageContext.request.contextPath }'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${pageContext.request.contextPath }",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      int _jspx_eval_c_005fset_005f0 = _jspx_th_c_005fset_005f0.doStartTag();
      if (_jspx_th_c_005fset_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005fset_005f0);
      _jspx_th_c_005fset_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fset_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fset_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005furl_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f0 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    boolean _jspx_th_c_005furl_005f0_reused = false;
    try {
      _jspx_th_c_005furl_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005furl_005f0.setParent(null);
      // /members/Payment.jsp(172,11) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005furl_005f0.setValue("/RevInsert");
      int _jspx_eval_c_005furl_005f0 = _jspx_th_c_005furl_005f0.doStartTag();
      if (_jspx_th_c_005furl_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f0);
      _jspx_th_c_005furl_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005furl_005f0, _jsp_getInstanceManager(), _jspx_th_c_005furl_005f0_reused);
    }
    return false;
  }
}
